version: 1
services:
  - type: web
    name: lasoiree-v1
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: python manage.py runserver 0.0.0.0:8000
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key
      - key: DATABASE_URL
        value: your-database-url
      - key: DEBUG
        value: 'true'
      - key: ALLOWED_HOSTS
        value: your-allowed-hosts
    autoDeploy: true
