version: 1
databases:
  - name: lasoiree_db
    plan: free
    databaseName: lasoiree
    user: lasoiree_user

services:
  - type: web
    name: lasoiree-v1
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py migrate
      python manage.py collectstatic --noinput
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lasoiree_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        generateValue: true
      - key: DJANGO_DEBUG
        value: "true"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,lasoiree-v1.onrender.com"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: DJANGO_SETTINGS_MODULE
        value: "backend.settings"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_SERVICE_SID
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: REDIS_URL
        fromService:
          type: redis
          name: lasoiree-redis
          property: connectionString
    autoDeploy: true
    healthCheckPath: /admin/login/
