version: 1
databases:
  - name: lasoiree_db
    plan: free
    databaseName: lasoiree
    user: lasoiree_user

services:
  - type: web
    name: lasoiree
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput

    startCommand: python manage.py runserver 0.0.0.0:8000

    releaseCommand: |
      python manage.py makemigrations
      python manage.py migrate

    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: lasoiree_db
          property: connectionString
      - key: DJANGO_SECRET_KEY
        sync: false
      - key: DJANGO_DEBUG
        value: "true"
      - key: ALLOWED_HOSTS
        value: ".onrender.com,lasoiree.onrender.com"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: DJANGO_SETTINGS_MODULE
        value: "backend.settings"
      - key: PYTHONUNBUFFERED
        value: "true"
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_SERVICE_SID
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false

    autoDeploy: true
