version: 1
services:
  - type: web
    name: your-service-name  # Replace with your service name
    env: python
    plan: free  # Change to your desired plan
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
    startCommand: python manage.py runserver 0.0.0.0:8000
    envVars:
      - key: DJANGO_SECRET_KEY
        value: your-secret-key  # Replace with your actual secret key
      - key: DATABASE_URL
        value: your-database-url  # Replace with your actual database URL
      - key: DEBUG
        value: 'false'  # Set to 'true' for development, 'false' for production
      - key: ALLOWED_HOSTS
        value: your-allowed-hosts  # Replace with your allowed hosts
    autoDeploy: true
