# Generated by Django 5.1.4 on 2025-02-20 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('venueservices', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='is_occupied',
            new_name='is_ongoing',
        ),
    ]
