# Generated by Django 5.1.4 on 2025-05-29 22:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('venueservices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='date',
            field=models.DateField(default=django.utils.timezone.now, editable=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='is_ongoing',
            field=models.BooleanField(default=True),
        ),
    ]
