# Generated by Django 5.1.4 on 2025-04-09 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authtoken_owner_alter_customuser_last_login_manager_and_more'),
        ('venueservices', '0002_rename_is_occupied_booking_is_ongoing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='waiter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bookings', to='authentication.waiter'),
        ),
    ]
