# Generated by Django 5.1.4 on 2025-01-08 20:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='otp_generated_at',
        ),
    ]
