# Generated by Django 5.1.4 on 2025-05-19 22:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manager',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='partner.venue'),
        ),
        migrations.AddField(
            model_name='manager',
            name='owners',
            field=models.ManyToManyField(related_name='managers', to='authentication.owner'),
        ),
        migrations.AddField(
            model_name='waiter',
            name='managers',
            field=models.ManyToManyField(related_name='waiters', to='authentication.manager'),
        ),
        migrations.AddField(
            model_name='waiter',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='partner.venue'),
        ),
    ]
