# Generated by Django 5.1.4 on 2025-04-11 11:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authtoken_owner_alter_customuser_last_login_manager_and_more'),
        ('partner', '0006_alter_menu_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='manager',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='authentication.owner'),
        ),
        migrations.AlterField(
            model_name='manager',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='managers', to='partner.venue'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='manager',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='waiters', to='authentication.manager'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='partner.venue'),
        ),
    ]
