# Generated by Django 5.1.4 on 2025-04-11 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_manager_owner_alter_manager_venue_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthToken',
        ),
    ]
