# Generated by Django 5.1.4 on 2025-04-11 14:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0004_delete_authtoken'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='email',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='is_location_permission_granted',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='location',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='name',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='manager',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='email',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='is_location_permission_granted',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='location',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='name',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='owner',
            name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='email',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='is_location_permission_granted',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='location',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='name',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='profile_photo',
        ),
        migrations.AddField(
            model_name='manager',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='owner',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='waiter',
            name='user',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='manager',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='waiter',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
