# Generated by Django 5.1.4 on 2025-04-11 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0005_remove_manager_email_remove_manager_gender_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestedOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, unique=True)),
                ('email', models.EmailField(max_length=254)),
                ('name', models.CharField(max_length=100)),
                ('business_name', models.CharField(max_length=255)),
                ('details', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=20)),
                ('pan_number', models.CharField(max_length=20)),
                ('owner_accepted', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined')], default='pending', max_length=10)),
            ],
        ),
    ]
