# Generated by Django 5.1.4 on 2025-04-11 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_requestedowner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='owner',
        ),
        migrations.RemoveField(
            model_name='waiter',
            name='manager',
        ),
        migrations.AddField(
            model_name='manager',
            name='owner',
            field=models.ManyToManyField(related_name='managers', to='authentication.owner'),
        ),
        migrations.AddField(
            model_name='waiter',
            name='manager',
            field=models.ManyToManyField(related_name='waiters', to='authentication.manager'),
        ),
    ]
