# Generated by Django 5.1.4 on 2025-05-10 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0008_rename_owner_manager_owners_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='interests',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='level',
            field=models.IntegerField(db_index=True, default=1),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='location',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
