from django.urls import path
from .views import (
    FetchVenuesView,
    BookingTableView,
    JoinTableView,
    SendWaiterNotificationView,
    AcceptBookingView,
    AddItemToCartView,
    GenerateBillView,
    EndBookingView,
    VenueMenuView,
    GetCurrentBookingDetailsView, 
    PresenceCheckInView, 
    PresenceLocationCheckView,
    VenueOngoingBookingsView,
    VenueStaffListView,
    UserVenuesListView,
    MonthlySalesView,
    DailySalesView
)

urlpatterns = [
    path('fetch_venues/', FetchVenuesView.as_view(), name='fetch_venues'),
    path('book_table/', BookingTableView.as_view(), name='book_table'),
    path('join_table/', JoinTableView.as_view(), name='join_table'),
    path('notify_waiters/', SendWaiterNotificationView.as_view(), name='send_waiter_notification'),
    path('accept_bookings/', AcceptBookingView.as_view(), name='accept_booking'),
    path('manage_cart/', AddItemToCartView.as_view(), name='add_item_to_cart'),
    path('generate_bill/', GenerateBillView.as_view(), name='generate_bill'),
    path('end_booking/', EndBookingView.as_view(), name='end_booking'),
    path('<str:venue_id>/view_menu/', VenueMenuView.as_view(), name='menu_view'),
    path('current_booking_details/', GetCurrentBookingDetailsView.as_view(), name='current_booking_details'),
    path('presence/check-in/', PresenceCheckInView.as_view(), name='presence-check-in'),
    path('presence/location-check/', PresenceLocationCheckView.as_view(), name='presence-location-check'),
    path('<str:venue_id>/ongoing_bookings/', VenueOngoingBookingsView.as_view(), name='venue_ongoing_bookings'),
    path('<str:venue_id>/staff_list/', VenueStaffListView.as_view(), name='venue_staff_list'),
    path('associated_venues/', UserVenuesListView.as_view(), name='user_venues_list'),
    path('<str:venue_id>/monthly_sales/', MonthlySalesView.as_view(), name='monthly_sales'),
    path('<str:venue_id>/daily_sales/', DailySalesView.as_view(), name='daily_sales'),
]
