# Generated by Django 5.1.4 on 2025-05-19 22:18

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, max_length=255, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True)),
                ('city', models.CharField(max_length=255)),
                ('geo_location', models.JSONField(null=True)),
                ('number_of_tables', models.PositiveIntegerField(default=0)),
                ('total_capacity', models.PositiveIntegerField(default=0)),
                ('current_strength', models.PositiveIntegerField(default=0)),
                ('venue_image', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
                ('qr_code', models.ImageField(blank=True, null=True, upload_to='venue_qrcodes/')),
                ('owners', models.ManyToManyField(related_name='venues', to='authentication.owner')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('is_occupied', models.BooleanField(default=False)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='partner.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_type', models.CharField(choices=[('FREE_DRINK', 'Free Drink'), ('PERCENTAGE_OFF', 'Percentage Off'), ('HAPPY_HOUR', 'Happy Hour'), ('BUY1_GET1', 'Buy 1 Get 1'), ('LASOIREE_LEVEL', 'LaSoiree Level Offer'), ('ENTRY_FEE', 'Entry Fee')], max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], null=True)),
                ('user', models.CharField(blank=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount (0-100)', max_digits=5, null=True)),
                ('is_entry_fee_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='partner.venue')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage discount (0-100)', max_digits=5, null=True)),
                ('is_available', models.BooleanField(default=True)),
                ('is_veg', models.BooleanField(default=True)),
                ('tag', models.CharField(choices=[('chef_special', 'Chef Special'), ('starter', 'Starter'), ('main_course', 'Main Course'), ('liquor', 'Liquor'), ('beverage', 'Beverage'), ('tobacco', 'Tobacco')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='partner.venue')),
            ],
        ),
    ]
