# Generated by Django 5.1.4 on 2025-02-17 19:49

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('city', models.CharField(max_length=255)),
                ('geo_location', models.JSONField()),
                ('number_of_tables', models.PositiveIntegerField()),
                ('venue_image', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField()),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('is_occupied', models.BooleanField(default=False)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='partner.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(max_length=255)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_veg', models.BooleanField(default=True)),
                ('tag', models.CharField(choices=[('starter', 'Starter'), ('beverage', 'Beverage'), ('main_course', 'Main Course'), ('dessert', 'Dessert')], max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='partner.venue')),
            ],
        ),
        migrations.CreateModel(
            name='Waiter',
            fields=[
                ('waiter_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='waiters', to='partner.venue')),
            ],
        ),
    ]
