# Generated by Django 5.1.4 on 2025-05-10 11:36

import django.core.validators
import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_id', models.CharField(editable=False, max_length=10, unique=True)),
                ('name', models.CharField(db_index=True, max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('category', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('gst_number', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('pan_number', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('city', models.CharField(db_index=True, max_length=255)),
                ('geo_location', models.JSONField(blank=True, default=dict, null=True)),
                ('number_of_tables', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_capacity', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('venue_image', models.ImageField(blank=True, null=True, upload_to='venue_images/')),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name', 'city'], name='partner_ven_name_f22f9d_idx')],
            },
        ),
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('qr_code', models.CharField(max_length=255, unique=True)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='qr_codes/')),
                ('is_occupied', models.BooleanField(db_index=True, default=False)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tables', to='partner.venue')),
            ],
            options={
                'ordering': ['venue', 'table_number'],
                'unique_together': {('venue', 'table_number')},
            },
        ),
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('offer_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('offer_type', models.CharField(choices=[('FREE_DRINK', 'Free Drink'), ('PERCENTAGE_OFF', 'Percentage Off'), ('HAPPY_HOUR', 'Happy Hour'), ('BUY1_GET1', 'Buy 1 Get 1'), ('LASOIREE_LEVEL', 'LaSoiree Level Offer'), ('ENTRY_FEE', 'Entry Fee')], db_index=True, max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('level', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], db_index=True, null=True)),
                ('user', models.CharField(blank=True, db_index=True, max_length=255, null=True)),
                ('start_date', models.DateTimeField(db_index=True)),
                ('end_date', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('discount_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_entry_fee_required', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='partner.venue')),
            ],
            options={
                'verbose_name': 'Offer',
                'verbose_name_plural': 'Offers',
                'ordering': ['-start_date'],
                'indexes': [models.Index(fields=['venue', 'is_active'], name='partner_off_venue_i_3c6343_idx'), models.Index(fields=['start_date', 'end_date'], name='partner_off_start_d_10a910_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR')), name='check_end_date_after_start_date'), models.CheckConstraint(condition=models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), name='discount_percentage_range')],
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('menu_item_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item_name', models.CharField(db_index=True, max_length=255)),
                ('item_description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage discount (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('is_available', models.BooleanField(db_index=True, default=True)),
                ('is_veg', models.BooleanField(db_index=True, default=True)),
                ('tag', models.CharField(choices=[('chef_special', 'Chef Special'), ('starter', 'Starter'), ('main_course', 'Main Course'), ('liquor', 'Liquor'), ('beverage', 'Beverage'), ('tobacco', 'Tobacco')], db_index=True, max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to='menu_images/')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_items', to='partner.venue')),
            ],
            options={
                'ordering': ['item_name'],
                'indexes': [models.Index(fields=['venue', 'is_available'], name='partner_men_venue_i_a3aa7f_idx'), models.Index(fields=['venue', 'tag'], name='partner_men_venue_i_7813c0_idx')],
            },
        ),
    ]
