# Generated by Django 5.1.4 on 2025-05-10 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
        ('partner', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={},
        ),
        migrations.RemoveConstraint(
            model_name='offer',
            name='check_end_date_after_start_date',
        ),
        migrations.RemoveConstraint(
            model_name='offer',
            name='discount_percentage_range',
        ),
        migrations.RemoveIndex(
            model_name='menu',
            name='partner_men_venue_i_a3aa7f_idx',
        ),
        migrations.RemoveIndex(
            model_name='menu',
            name='partner_men_venue_i_7813c0_idx',
        ),
        migrations.RemoveIndex(
            model_name='offer',
            name='partner_off_venue_i_3c6343_idx',
        ),
        migrations.RemoveIndex(
            model_name='offer',
            name='partner_off_start_d_10a910_idx',
        ),
        migrations.RemoveIndex(
            model_name='venue',
            name='partner_ven_name_f22f9d_idx',
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='venue',
            name='owners',
            field=models.ManyToManyField(related_name='venues', to='authentication.owner'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage discount (0-100)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_veg',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tag',
            field=models.CharField(choices=[('chef_special', 'Chef Special'), ('starter', 'Starter'), ('main_course', 'Main Course'), ('liquor', 'Liquor'), ('beverage', 'Beverage'), ('tobacco', 'Tobacco')], max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount (0-100)', max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('FREE_DRINK', 'Free Drink'), ('PERCENTAGE_OFF', 'Percentage Off'), ('HAPPY_HOUR', 'Happy Hour'), ('BUY1_GET1', 'Buy 1 Get 1'), ('LASOIREE_LEVEL', 'LaSoiree Level Offer'), ('ENTRY_FEE', 'Entry Fee')], max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='venue',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='geo_location',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='number_of_tables',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='venue',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='total_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
