# Generated by Django 5.1.4 on 2025-04-09 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_authtoken_owner_alter_customuser_last_login_manager_and_more'),
        ('partner', '0001_initial'),
        ('venueservices', '0003_alter_booking_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='venues', to='authentication.owner'),
        ),
        migrations.DeleteModel(
            name='Waiter',
        ),
    ]
