# Generated by Django 5.1.4 on 2025-04-09 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_venue_owner_delete_waiter'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='total_capacity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
