# Generated by Django 5.1.4 on 2025-01-16 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0002_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='is_occupied',
            field=models.BooleanField(default=False),
        ),
    ]
