# Generated by Django 5.1.4 on 2025-04-11 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0004_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage discount (0-100)', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='menu',
            name='item_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
