# Generated by Django 5.1.4 on 2025-04-11 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0006_alter_menu_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='category',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='venue',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
