# Generated by Django 5.1.4 on 2025-04-11 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0006_requestedowner'),
        ('partner', '0007_venue_category_venue_description_venue_gst_number_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venue',
            name='owner',
        ),
        migrations.AddField(
            model_name='venue',
            name='owners',
            field=models.ManyToManyField(related_name='venues', to='authentication.owner'),
        ),
    ]
