# Generated by Django 5.1.4 on 2025-04-11 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0008_remove_venue_owner_venue_owners'),
    ]

    operations = [
        migrations.AlterField(
            model_name='venue',
            name='geo_location',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='number_of_tables',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
