# Generated by Django 5.1.4 on 2025-05-10 08:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('partner', '0009_alter_venue_geo_location_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['item_name']},
        ),
        migrations.AlterModelOptions(
            name='table',
            options={'ordering': ['venue', 'table_number']},
        ),
        migrations.AlterModelOptions(
            name='venue',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='venue',
            name='owners',
        ),
        migrations.AlterField(
            model_name='menu',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Percentage discount (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_available',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='is_veg',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='item_name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='menu',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tag',
            field=models.CharField(choices=[('chef_special', 'Chef Special'), ('starter', 'Starter'), ('main_course', 'Main Course'), ('liquor', 'Liquor'), ('beverage', 'Beverage'), ('tobacco', 'Tobacco')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='discount_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Percentage discount (0-100)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)]),
        ),
        migrations.AlterField(
            model_name='offer',
            name='end_date',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='level',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Level 1'), (2, 'Level 2'), (3, 'Level 3'), (4, 'Level 4'), (5, 'Level 5')], db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='offer_type',
            field=models.CharField(choices=[('FREE_DRINK', 'Free Drink'), ('PERCENTAGE_OFF', 'Percentage Off'), ('HAPPY_HOUR', 'Happy Hour'), ('BUY1_GET1', 'Buy 1 Get 1'), ('LASOIREE_LEVEL', 'LaSoiree Level Offer'), ('ENTRY_FEE', 'Entry Fee')], db_index=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='offer',
            name='start_date',
            field=models.DateTimeField(db_index=True),
        ),
        migrations.AlterField(
            model_name='offer',
            name='user',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='is_occupied',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name='table',
            name='table_number',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='category',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='city',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='geo_location',
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='gst_number',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='name',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='venue',
            name='number_of_tables',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='venue',
            name='pan_number',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='total_capacity',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together={('venue', 'table_number')},
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['venue', 'is_available'], name='partner_men_venue_i_a3aa7f_idx'),
        ),
        migrations.AddIndex(
            model_name='menu',
            index=models.Index(fields=['venue', 'tag'], name='partner_men_venue_i_7813c0_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['venue', 'is_active'], name='partner_off_venue_i_3c6343_idx'),
        ),
        migrations.AddIndex(
            model_name='offer',
            index=models.Index(fields=['start_date', 'end_date'], name='partner_off_start_d_10a910_idx'),
        ),
        migrations.AddIndex(
            model_name='venue',
            index=models.Index(fields=['name', 'city'], name='partner_ven_name_f22f9d_idx'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR')), name='check_end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='offer',
            constraint=models.CheckConstraint(condition=models.Q(('discount_percentage__gte', 0), ('discount_percentage__lte', 100)), name='discount_percentage_range'),
        ),
    ]
